version: '3'
services:
  cake-manager-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:8088
    depends_on:
      - h2db

  h2db:
    image: oscarfonts/h2
    ports:
      - 1521:1521
    environment:
      - H2_OPTIONS=-ifNotExists
    volumes:
      - ./data:/h2-data
